version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5438:5438
    environment:
      POSTGRES_DB: postgres 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
